### PR TITLE
Alejandro/player game

### PR DESCRIPTION
**Pull request by ale1311sv**

### CODE REVIEW

**Comment by nurietzsche2021** [comment]
I suggest that you restructure the handle_event for "cell_selected" so it can analyse different possible errors. First of all, I would remake the the state you're making in new initializing first_cell_selected on nil. This way, you can distinguish between first_cell and second_cell selection using simple if is_nil(socket.assigns.you.first_cell_selected) structure. Indeed, right now the conditions to check to which cell corresponds the selection (first or second) are not well written (what makes the difference now between the first cell and second cell selection is checking if socket.assigns.you.first_cell_selected is equal to {} or not, you were checking if second cell coincided with first_cell_select with what you've written). 

I would check for possible errors of second cell selection after invoking second_cell_selected. That way, you can be consistent with what this function does (I suppose it inserts the boat in socket.assigns.you.boats). In particular, I'd check with cond do structure:
- First: If one of selected cells is invalid (using is_cell_valid?(cell)) respond adequate error
- Then: If cell selection is legal (using my is_it_a_boat?(cell, cell)) respond adequate error
- Later: If cell selection doesn't match the requested length of boat (using my was_boat_selection_right?(cell, cell, integer))
- Lastly: (if true) invoke second_cell_selected (maybe rename the name of the function so it's more readable).
I also suggest writing variable names to simplify our reading. Specially, to use my functions that I've indicated above.

**Review by nurietzsche2021 — CHANGES_REQUESTED** [review]
I suggest that you restructure the handle_event for "cell_selected" so it can analyse different possible errors. First of all, I would remake the the state you're making in new initializing first_cell_selected on nil. This way, you can distinguish between first_cell and second_cell selection using simple if is_nil(socket.assigns.you.first_cell_selected) structure. Indeed, right now the conditions to check to which cell corresponds the selection (first or second) are not well written (what makes the difference now between the first cell and second cell selection is checking if socket.assigns.you.first_cell_selected is equal to {} or not, you were checking if second cell coincided with first_cell_select with what you've written).

I would check for possible errors of second cell selection after invoking second_cell_selected. That way, you can be consistent with what this function does (I suppose it inserts the boat in socket.assigns.you.boats). In particular, I'd check with cond do structure:

First: If one of selected cells is invalid (using is_cell_valid?(cell)) respond adequate error
Then: If cell selection is legal (using my is_it_a_boat?(cell, cell)) respond adequate error
Later: If cell selection doesn't match the requested length of boat (using my was_boat_selection_right?(cell, cell, integer))
Lastly: (if true) invoke second_cell_selected (maybe rename the name of the function so it's more readable).
I also suggest writing variable names to simplify our reading. Specially, to use my functions that I've indicated above.

**Comment by ale1311sv** [comment]
Nuria, I change the code, taking your suggestions seriously. Changed the initialization of first_cell_selected to nil instead of an empty tuple and the functions below to an is_nil Kernel guard. Also, changed the cond do structure with the whole correspondent errors.

Tomorrow, i'll implement the second_cell_selected function, which is in charge of "drawing" the boat. When I finish that function mentioned before, the :setting mode will be finished, moving on to the :game mode.

Thanks, Nuria!

**Review by nurietzsche2021 — APPROVED** [review]
You should only now import my module and invoke my functions. I don't see the point on writing explicitly not is_nil(...) in the cond do structure. One thing can be nil or not be it, there's only two options! So I think, again, using if is_nil .. else ... structure looks more clear. At least, if you insist on using cond do structure for this, change not is_nil for true (which is equivalent and shows your understanding of is_nil dicotomy, knowing that if execution doesn't match is_nil will always be not is_nil and you could make this option "default" by condition: true).

**Pull request merged**
