### PR TITLE
TESTS FINISHED

### PR DESCRIPTION
**Pull request by nurietzsche2021**
I've already tested all my operations successfully and also I've changed
one of their names because it had a typographic mistake. That's the only
thing I've changed in lib, this function name and its invokations

### CODE REVIEW

**Comment by olirods** [comment]
Great operations.ex, you just need docs in some functions, don't you?

**Comment by olirods** [comment]
Tests are also great! Congrats

**Review by olirods — APPROVED** [review]

**Comment by nurietzsche2021** [comment]
> Great operations.ex, you just need docs in some functions, don't you?

Sergio, I actually didn't doc functions when they were so clear and simple that was unnecessary. If you consider there's any function not clear that I should document, please, let me know.

**Review by ale1311sv — APPROVED** [review]
Nice job with the tests, Nuria!

**Pull request merged**
